[package]
name = "jr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.9.0"
itertools = "0.10.3"
log = "0.4.17"
ndarray = "0.15.6"
